### ISSUE TITLE
Comfyui-Griptape LM Studio

### ISSUE THREAD

**Issue by freshlesh3** [Banbury/griptape-llama#1]
Hi. Not sure if you are familiar with the Comfyui implementation of Griptape, but could you walk us through how to connect LM Studio to the Comfyui version, if you're familiar with it.

**Comment by Banbury** [comment]
I'd love to help you, but I find it easier to code than using ComfyUI. If you have specific questions or problems using LM Studio, then ping me on the Griptape Discord server.

**Comment by freshlesh3** [comment]
> I'd love to help you, but I find it easier to code than using ComfyUI. If you have specific questions or problems using LM Studio, then ping me on the Griptape Discord server.

Thanks for the reply.  I see that they updated the ComfyUI custom nodes with new prompt drivers that include local LLMs like Ollama and alternate pipelines, thanks for the response though. I've added a link to the Griptape video showing the new nodes should anyone else need them.
https://youtu.be/jIq_TL5xmX0
